### ISSUE TITLE
Planejamento das Fases e/ou Iterações do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-Echoeasy#2]
Aqui, devem estar exclusivamente, as atividades relacionadas ao desenvolvimento do produto que vcs vão fazer.
PBB e USM, por exemplo, não fazem parte do projeto.

**Comment by LucasGSAntunes** [comment]
Aguardando definição do backlog para entrega de iterações mais detalhadas
